<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWRDJjxx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWRDJjxx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWRDJjxx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWRDJjxx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWRDJjxx\App_KernelDevDebugContainer([
    'container.build_hash' => 'WRDJjxx',
    'container.build_id' => 'e9f059d4',
    'container.build_time' => 1646061469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWRDJjxx');
